/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Experience: typeof import('./src/components/Experience.vue')['default']
    ExperienceTimeline: typeof import('./src/components/common/ExperienceTimeline.vue')['default']
    Footer: typeof import('./src/components/layouts/Footer.vue')['default']
    Header: typeof import('./src/components/layouts/Header.vue')['default']
    InfoCard: typeof import('./src/components/common/InfoCard.vue')['default']
    Introduction: typeof import('./src/components/Introduction.vue')['default']
    ProjectCard: typeof import('./src/components/common/ProjectCard.vue')['default']
    ProjectCardDisplay: typeof import('./src/components/common/ProjectCardDisplay.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillCard: typeof import('./src/components/common/SkillCard.vue')['default']
    SkillCardDisplay: typeof import('./src/components/common/SkillCardDisplay.vue')['default']
    TechStack: typeof import('./src/components/TechStack.vue')['default']
    Timeline: typeof import('primevue/timeline')['default']
  }
}
